# yaml-language-server: $schema=../_validation/schemas/role.schema.json
# Role: Analyst
# =============

code: "anl"
name: "Analyst"
type: "person"
level: "project"
desc: "Read-focused role for exploring and consuming data"
disabled: false
required: false

privileges:
  computes:
    default:
      all: [USAGE]
  layers:
    mart:
      all:
        - USAGE
        - SELECT ON TABLES
        - SELECT ON VIEWS
        - USAGE ON FUNCTIONS
        - USAGE ON PROCEDURES
    expose:
      all:
        - USAGE
        - SELECT ON TABLES
        - SELECT ON VIEWS
        - USAGE ON FUNCTIONS
        - USAGE ON PROCEDURES
    temporary:
      all:
        - USAGE
        - MODIFY
        - CREATE TABLE
        - CREATE VIEW
        - SELECT ON TABLES
        - INSERT ON TABLES
        - UPDATE ON TABLES
        - DELETE ON TABLES
        - TRUNCATE ON TABLES
        - SELECT ON VIEWS
