# yaml-language-server: $schema=../_validation/schemas/role.schema.json
# Role: Operator
# ==============

code: "opr"
name: "Operator"
type: "person"
level: "project"
desc: "Elevated access for project-level operational support and incident response"
disabled: true
required: false

privileges:
  computes:
    default:
      all: [USAGE, OPERATE, MONITOR]
    ingest:
      all: [USAGE, OPERATE, MONITOR]
    transform:
      all: [USAGE, OPERATE, MONITOR]
  layers:
    source: {all: full}
    staging: {all: full}
    integration: {all: full}
    mart: {all: full}
    expose: {all: full}
    temporary: {all: full}
  roles:
    transform: [all]
    ingest: [all]
    engineer: [all]
    analyst: [all]
    reporting: [all]
