version: 2


models:
  - name: int__generic__environment
    description: Collection of Environments

    data_tests:
      - has_data:
          name: int__generic__environment__has_data

    columns:
      - name: environment_code
        description: Unique code for the environment
        data_type: varchar(20)

        data_tests:
          - not_null:
              name: int__generic__environment__environment_code__not_null

          - unique:
              name: int__generic__environment__environment_code__unique

          - not_empty:
              name: int__generic__environment__environment_code__not_empty

      - name: environment_name
        description: Unique name for the environment
        data_type: varchar(200)

        data_tests:
          - not_null:
              name: int__generic__environment__environment_name__not_null

          - unique:
              name: int__generic__environment__environment_name__unique

          - not_empty:
              name: int__generic__environment__environment_name__not_empty

      - name: environment_alias
        description: Short alias for the environment
        data_type: varchar

      - name: environment_desc
        description: Description of the environment
        data_type: varchar

      - name: environment_sort
        description: Sort order for the environment
        data_type: integer
