# yaml-language-server: $schema=../../_validation/schemas/role.schema.json
# Role: Administrator
# ===================

code: "adm"
name: "Admin"
type: "person"
level: "platform"
desc: "Full administrative control across the platform and all Projects"
disabled: true
required: false
