# yaml-language-server: $schema=../_validation/schemas/user.schema.json
# Written by `just sf bootstrap` for ADMIN.

login: "ADMIN"
create: false
roles:
  - project: example
    role: engineer
    environments:
      - development
